### ISSUE TITLE
Mod compats?

### ISSUE THREAD

**Issue by Therkelsen** [miyucomics/sparkle#7]
Hi there!

Would you consider adding compatibility with mods like [Universal Ores](https://www.curseforge.com/minecraft/mc-mods/universal-ores-fabric) and [Rechiseled](https://www.curseforge.com/minecraft/mc-mods/rechiseled)?

**Comment by miyucomics** [comment]
Hi! I notice you're mentioning Echos of the Wild which is a modpack you made. That's really cool! You can add your own compatibility with a simple datapack by adding to the `sparkly` tag for blocks and items. I don't plan on adding mod compatibility by default since I don't want to manually sift through dozens of modded blocks just to add cases most players won't see.

**Comment by Therkelsen** [comment]
I see! I'll consider it, thanks for the quick reply!
